export enum Modals {
    DOWNLOAD_HELPER_NOT_ENOUGH_SPACE,
    LANDING_COULD_NOT_FIND_CLIENT,
    LANDING_NOT_ENOUGH_DISK_SPACE,
    LANDING_NOT_ENOUGH_DISK_SPACE_CLIENT,
    LANDING_DIRECTORY_NOT_EMPTY,
    VERSION_CHECKER_NEW_VERSION_AVAILABLE,
    SETTINGS_INVALID_SETTING,
    SETTINGS_SAVED,
    SETTINGS_RESET,
    SETTINGS_COULD_NOT_FIND_CLIENT,
    ADDON_COULD_NOT_FIND_DOWNLOADFILE
}